namespace Database.Resource.Enum
{
    public enum DressSlot
    {
        HELM,
        ARMOR,
        PANTS,
        BOOTS,
        MANTLE,
        GLOVES,
        BRACERS,
        BELT,
        RING1,
        RING2,
        EARRINGS,
        NECKLACE,
        CLOAK,
        SHIRT,
        MAINHAND,
        OFFHAND,
        RANGED,
        AMMO,
        TABARD,
        TRINKET,
        BAG,
        DEATHINSURANCE,
        LIFESTYLEHEAD,
        LIFESTYLEBACK,
        LIFESTYLESUIT,
        LIFESTYLEUNDERWEAR,
        UNDRESSABLE,
        TWOHANDED,
        DUALWIELD,
        RING
    }
}